### ISSUE TITLE
Since updating to ver 201 there’s an error causing the hub service to restart every 10 minutes. 

### ISSUE THREAD

**Issue by elycohen** [nitaybz/homebridge-switcher-boiler#8]
Thanks for a great plugin. 
Since updating to ver 201 there’s an error causing the hub service to restart every 10 minutes. 

Log:

[9/26/2020, 01:49:16] [Robot Vaccum ] INF getFirmware | roborock.vacuum.s5 | Firmwareversion is 3.5.7_002008
[9/26/2020, 01:49:17] [Robot Vaccum ] INF getFirmware | roborock.vacuum.s5 | Firmwareversion is 3.5.7_002008
[9/26/2020, 01:57:11] TypeError: message_buffer.byteLength is not a function
    at Function.is_valid (/usr/local/lib/node_modules/homebridge-switcher-boiler/node_modules/switcher-js/src/switcher.js:44:33)
    at Socket.<anonymous> (/usr/local/lib/node_modules/homebridge-switcher-boiler/node_modules/switcher-js/src/switcher.js:272:37)
    at Socket.emit (events.js:315:20)
    at UDP.onMessage (dgram.js:910:8)
[9/26/2020, 01:57:11] Got SIGTERM, shutting down Homebridge...
[9/26/2020, 01:57:12] TypeError: message_buffer.byteLength is not a function
    at Function.is_valid (/usr/local/lib/node_modules/homebridge-switcher-boiler/node_modules/switcher-js/src/switcher.js:44:33)
    at Socket.<anonymous> (/usr/local/lib/node_modules/homebridge-switcher-boiler/node_modules/switcher-js/src/switcher.js:272:37)
    at Socket.emit (events.js:315:20)
    at UDP.onMessage (dgram.js:910:8)
[9/26/2020, 01:57:16] [HB Supervisor] Homebridge Process Ended. Code: 143, Signal: null
[9/26/2020, 01:57:21] [HB Supervisor] Restarting Homebridge...
[9/26/2020, 01:57:21] [HB Supervisor] Started Homebridge v1.2.3 with PID: 1013
[9/26/2020, 01:57:22] Loaded config.json with 8 accessories and 3 platforms.

**Comment by elycohen** [comment]
At the previous version I had poll interval set to 600 (10 min) maybe its somehow related. 
After updating and noticing this behavior, I uninstalled the plugin and then installed it again. 
Issue remained. 

Thanks.

**Comment by nitaybz** [comment]
fixed
